### ISSUE TITLE
profile: check some box

### ISSUE THREAD

**Issue by 700software** [Skewjo/SysLat_Website#6]
https://github.com/settings/profile

![image](https://user-images.githubusercontent.com/20981023/99203718-0f878d80-2779-11eb-9d1c-38a93f2a43a1.png)
![image](https://user-images.githubusercontent.com/20981023/99203768-347c0080-2779-11eb-91a4-5462938f0f81.png)

**Comment by Skewjo** [comment]
done, thanks
